---
- hosts: dev
  become: yes
  remote_user: ec2-user
  tasks:
  - name: Update S3 code bucket
    command: aws s3 sync /var/www/html/ s3://{{ s3code }}/ --delete
  - shell: echo "define('SITEURL','http:dev."{{ domain }}".com');" >> index.html
    args:
      chdir: /var/www/html/
  - shell: echo "define('HOME','http://dev."{{ domain }}".com');" >> index.html
    args:
      chdir: /var/www/html/